Description: Pandoc AWS Lambda Layer 
Parameters:
  AllowedPrincipal:
    Type: String
    Description: Account principal allowed to deploy this layer
    Default: '*'

Resources:
  PandocLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs8.10
        - nodejs6.10
        - python3.6
        - python3.7
        - python2.7
        - ruby2.5
        - java-1.8.0-openjdk
        - go1.x
        - dotnetcore2.1
        - dotnetcore2.0
        - dotnetcore1.0
      Description: Pandoc for AWS Lambda
      LayerName: pandoc
      LicenseInfo: GPL-2.0-or-later
      Content:
        S3Bucket: DEPLOYMENT_BUCKET_NAME
        S3Key: DEPLOYMENT_KEY

  DeploymentPermission:
    Type: "AWS::Lambda::LayerVersionPermission"
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref PandocLayer
      Principal: !Ref AllowedPrincipal

Outputs:
  PandocLayer: 
    Value: !Ref PandocLayer
